title: Avi Tattoos & Piercing
description: בוטיק קעקועים ופירסינג מקצועי
baseurl: "" 
url: "https://your-username.github.io"

collections:
  tattoos:
    output: true
    permalink: /blog/tattoos/:path/
  piercing:
    output: true
    permalink: /blog/piercing/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude: [node_modules, package.json, Tailwind.config.js]
